run:
  mode: 'Test'

transforms:
  - 

dataset:
  class_name: "ISIC2020Dataset"
  params:
    - root_directory: "../data/isic2020"

  number_classes: 2

  train: 
    batch_size: 4
    shuffle: true
    worker: 1
  
  validation: 
    batch_size: 4
    shuffle: true
    worker: 1

  test:
    batch_size: 4
    shuffle: true
    worker: 1

training:
  lr: 0.002
  patience: 5
  epochs: 50
  progress_p: 

model:
  pretrained: false
  save_path: './saved_models/s'

# preprocess:

